run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  cyclop:
    max-complexity: 15
  funlen:
    lines: 80
    statements: 50
  gocognit:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  gocyclo:
    min-complexity: 15
  godot:
    scope: declarations
    exclude:
      - "^fixme:"
      - "^todo:"
  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK
  gomnd:
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US
  nestif:
    min-complexity: 4
  nlreturn:
    block-size: 2
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  revive:
    rules:
      - name: exported
      - name: unexported-return
      - name: time-naming
      - name: var-declaration
      - name: package-comments
      - name: range-val-in-closure
      - name: go-naming
      - name: val-in-range
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: indent-error-flow
  varnamelen:
    min-name-length: 2
    ignore-names:
      - err
      - id
      - v
      - f
      - e
      - i
      - j
      - k
      - x
      - y
      - z
    ignore-decls:
      - v Vector3
      - f *Face
      - e *Edge
      - p *Polyhedron

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gochecknoglobals
        - gocognit
        - goconst
        - cyclop
        - lll
        - dupl
        - goerr113
        - varnamelen
        - exhaustruct
        - maintidx
    - path: examples/
      linters:
        - gomnd
        - gochecknoglobals
        - forbidigo
        - wrapcheck
    - path: benchmark_test\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - cyclop
    - linters:
        - lll
      source: "^//go:generate "
  max-issues-per-linter: 0
  max-same-issues: 0