version: 2

project_name: conway

before:
  hooks:
    - go mod tidy

builds:
  - id: examples-basic
    main: ./main.go
    dir: ./examples/basic
    binary: conway-basic
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: examples-advanced
    main: ./main.go
    dir: ./examples/advanced
    binary: conway-advanced
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

dockers:
  - image_templates:
      - "ghcr.io/sksmith/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/sksmith/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: auto
    use: buildx

snapshot:
  version_template: "{{ .Tag }}-next"

release:
  draft: false
  prerelease: auto
  name_template: "Release {{ .Tag }}"
  header: |
    ## Conway Polyhedron Notation Library {{ .Tag }}
    
    This release includes the Conway polyhedron notation library and example applications.
  footer: |
    ## Installation
    
    ### As a Go library:
    ```bash
    go get github.com/sksmith/conway@{{ .Tag }}
    ```
    
    ### Binary releases:
    Download the appropriate binary for your platform from the assets below.
    
    ### Docker:
    ```bash
    docker pull ghcr.io/sksmith/conway:{{ .Tag }}
    ```

  extra_files:
    - glob: ./README.md
    - glob: ./LICENSE